---
- name: Install nginx
  yum: name=nginx state=present
  become: yes

- name: Remove default nginx config
  file: path=/etc/nginx/sites-enabled/default state=absent
  notify:  restart-nginx
  become: yes

- name: Force restart-nginx              #force ACTIVE handlers!!!
  meta: flush_handlers
  become: yes

- name: Setup default nginx configuration
  template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf owner=root group=root mode=0644
  notify: restart-nginx
  become: yes