---
- name: systemd daemon reload
  systemd:
    daemon_reload: yes
  become: yes

- name:  restart service jenkins
  service: 'name={{ user_name }}.service enabled=yes  state=restarted'
  become: yes

