---
- name: Create  group -  sonar w gid
  group:
    name: "{{ user_name }}"
    state: present
    gid: 6000
  become: yes
  
- name: Create  user sonar w  uid
  user:
    name: "{{ user_name }}"
    append: yes
    uid: 6000
    group: 6000
  become: yes

#for troubleshooting
- name: Add sudoers priveleges  in a separate file
  copy:
    dest: /etc/sudoers.d/{{ user_name }}
    content: " {{ user_name }} ALL=(ALL) NOPASSWD:ALL"
  become: yes